#!/usr/bin/env python3
"""Chunk a corpus census across PBS Pro jobs (one array job, N chunks).

The census is I/O bound on Lustre, not CPU bound, so throughput scales with the
number of nodes hitting the filesystem rather than with cores per node. Running
everything from a login node caps you at that node's share of the filesystem
(measured: ~11 jobs/s aggregate, ~16 h for 621k jobs). Spreading the same roots
over N compute nodes multiplies the available bandwidth.

This bin-packs the roots into N chunks of roughly equal job count, writes a
manifest plus a PBS array-job script, and leaves you one shard per chunk to
merge at the end. Shards are named by chunk index, so two chunks can never
collide on an output path no matter how the roots are distributed.

Stdlib only. Generates scripts; submits only with --submit.

Usage:
    python submit_census_pbs.py census_roots_final.json -A myproject -q prod
    python submit_census_pbs.py census_roots_final.json -A myproject -q prod \\
        --chunks 16 --walltime 04:00:00 --workers 32 --submit
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

PBS_TEMPLATE = """#!/bin/bash -l
# Generated by submit_census_pbs.py -- one array task per root chunk.
#PBS -N {name}
#PBS -A {account}
#PBS -q {queue}
#PBS -l select={select}
{place_directive}#PBS -l walltime={walltime}
{filesystems_directive}{rerunnable_directive}{extra_directives}#PBS -j oe
#PBS -o {logdir}/

cd "${{PBS_O_WORKDIR:-{workdir}}}"

# conda's shell functions reference unset variables ($PS1, $_CE_M, $CONDA_SHLVL),
# so `set -u` must not be active while activating an environment -- it aborts the
# job in the first second with a bare "PS1: unbound variable" and no output.
set +u
{env_setup}set -u

# Preamble: every one of these has cost a blind resubmit at least once, so the
# log states them up front. A failure log that stops partway through this block
# names its own cause.
echo "=== census chunk preamble ==="
echo "host      : $(hostname)"
echo "pwd       : $(pwd)"
echo "python    : $(command -v python || echo 'NOT FOUND')"
echo "conda env : ${{CONDA_DEFAULT_ENV:-<none active>}}"
if ! python -c "import oact_utilities.workflows.census" 2>&1; then
    echo "FATAL: cannot import oact_utilities.workflows.census" >&2
    echo "       (wrong conda env, or the package is not installed here)" >&2
    exit 1
fi
echo "census    : importable"
echo "============================="

MANIFEST="{manifest}"
SHARD_DIR="{shard_dir}"
IDX="${{CENSUS_CHUNK:-${{PBS_ARRAY_INDEX:-0}}}}"
LABEL=$(printf 'chunk%02d' "$IDX")

mkdir -p "$SHARD_DIR"

# Pull this task's roots out of the manifest. Chunk index drives the shard name,
# so no two tasks can ever target the same output file. Read with a while loop
# rather than `mapfile`, which is a bash 4 builtin -- this has to work wherever
# /bin/bash happens to be old.
ROOT_LIST=$(python -c "
import json
print('\\n'.join(json.load(open('$MANIFEST'))[$IDX]))
") || {{
    echo "chunk $IDX: could not read chunk $IDX from $MANIFEST" >&2
    exit 1
}}

ROOTS=()
while IFS= read -r line; do
    [ -n "$line" ] && ROOTS+=("$line")
done <<< "$ROOT_LIST"

if [ "${{#ROOTS[@]}}" -eq 0 ]; then
    echo "chunk $IDX: manifest holds no roots for this index" >&2
    exit 1
fi

echo "chunk $IDX on $(hostname): ${{#ROOTS[@]}} root(s), {workers} workers"
for r in "${{ROOTS[@]}}"; do echo "  $r"; done

python -m oact_utilities.workflows.census "${{ROOTS[@]}}" \\
    -o "$SHARD_DIR/$LABEL{suffix}" \\
    --format {fmt} \\
    --workers {workers}
rc=$?
echo "chunk $IDX exit=$rc"
exit $rc
"""


def count_jobs(root: str) -> int:
    """Number of immediate subdirectories (job dirs) under a root."""
    try:
        with os.scandir(root) as it:
            return sum(1 for e in it if e.is_dir(follow_symlinks=False))
    except OSError:
        return 0


def bin_pack(sized: list[tuple[str, int]], n: int) -> list[list[tuple[str, int]]]:
    """Greedy longest-processing-time-first packing into n buckets."""
    buckets: list[list[tuple[str, int]]] = [[] for _ in range(n)]
    loads = [0] * n
    for root, size in sorted(sized, key=lambda t: -t[1]):
        i = loads.index(min(loads))
        buckets[i].append((root, size))
        loads[i] += size
    return [b for b in buckets if b]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("roots_file", help="JSON array of job roots")
    p.add_argument("-A", "--account", required=True, help="PBS account/project")
    p.add_argument("-q", "--queue", required=True, help="PBS queue")
    p.add_argument("--chunks", type=int, default=8, help="Array tasks (default: 8)")
    p.add_argument(
        "--workers", type=int, default=32, help="Threads per task (default: 32)"
    )
    p.add_argument(
        "--select",
        default=None,
        help="Full PBS -l select value. Sites differ: ALCF Crux wants "
        "'1:system=crux', others '1:ncpus=N'. Default: '1:ncpus=<workers>'. "
        "Copy it from a PBS script that already works on your machine.",
    )
    p.add_argument(
        "--place",
        default=None,
        help="PBS -l place value (e.g. 'scatter'). Omitted when unset.",
    )
    p.add_argument(
        "--pbs",
        action="append",
        default=[],
        metavar="DIRECTIVE",
        help="Extra raw #PBS directive, repeatable (e.g. --pbs '-l foo=1')",
    )
    p.add_argument(
        "--walltime", default="06:00:00", help="Per-task walltime (default: 06:00:00)"
    )
    p.add_argument(
        "--filesystems",
        default="home:eagle",
        help="ALCF filesystems directive; pass '' to omit (default: home:eagle)",
    )
    p.add_argument(
        "--outdir",
        default=os.path.expanduser("~/census_out"),
        help="Where shards, logs, and manifest go (default: ~/census_out)",
    )
    p.add_argument(
        "--format",
        choices=("parquet", "sqlite", "csv"),
        default=None,
        help="Shard format (default: parquet if pyarrow importable, else sqlite)",
    )
    p.add_argument("--conda-env", default=None, help="Conda env to activate in the job")
    p.add_argument("--conda-base", default=None, help="Conda install prefix")
    p.add_argument(
        "--venv", default=None, help="Virtualenv to activate instead of conda"
    )
    p.add_argument(
        "--rerunnable",
        choices=("y", "n"),
        default="y",
        help="PBS -r value. PBS Pro REFUSES a non-rerunnable array job "
        "('cannot submit non-rerunable Array Job'), and some sites default to "
        "-r n, so this is emitted explicitly as 'y' (default).",
    )
    p.add_argument(
        "--no-array",
        action="store_true",
        help="Emit N independent jobs instead of one array job, plus a "
        "submit_all.sh that qsubs them with -v CENSUS_CHUNK=<i>. Use this when "
        "the site restricts or disallows array jobs.",
    )
    p.add_argument("--name", default="census", help="PBS job name (default: census)")
    p.add_argument("--submit", action="store_true", help="Actually qsub the array job")
    args = p.parse_args()

    fmt = args.format
    if fmt is None:
        try:
            import pyarrow  # noqa: F401

            fmt = "parquet"
        except ImportError:
            fmt = "sqlite"
            print("pyarrow not importable here: defaulting shards to sqlite.\n")
    suffix = {"parquet": ".parquet", "sqlite": ".db", "csv": ".csv"}[fmt]
    select = args.select if args.select else f"1:ncpus={args.workers}"

    roots = [str(r).rstrip("/") for r in json.load(open(args.roots_file))]
    for a in roots:
        for b in roots:
            if a != b and b.startswith(a + "/"):
                print(f"Error: {a} contains {b}; remove the parent", file=sys.stderr)
                return 1
    missing = [r for r in roots if not os.path.isdir(r)]
    if missing:
        print(f"Error: {len(missing)} root(s) do not exist:", file=sys.stderr)
        for r in missing:
            print(f"  {r}", file=sys.stderr)
        return 1

    print(f"Counting job dirs under {len(roots)} root(s)...")
    sized = [(r, count_jobs(r)) for r in roots]
    for r, n in sized:
        if n == 0:
            print(f"  Warning: {r} holds no subdirectories -- skipping")
    sized = [(r, n) for r, n in sized if n > 0]
    if not sized:
        print("Error: no root holds any job directories", file=sys.stderr)
        return 1
    total = sum(n for _, n in sized)
    print(f"  {total:,} job directories\n")

    chunks = bin_pack(sized, args.chunks)
    print(f"{'chunk':<9}{'roots':>7}{'jobs':>12}")
    print("-" * 28)
    for i, c in enumerate(chunks):
        print(f"chunk{i:02d}  {len(c):>7}{sum(n for _, n in c):>12,}")
    spread = [sum(n for _, n in c) for c in chunks]
    print(f"\nbalance: largest {max(spread):,} vs smallest {min(spread):,}")

    outdir = os.path.abspath(os.path.expanduser(args.outdir))
    shard_dir = os.path.join(outdir, "shards")
    logdir = os.path.join(outdir, "logs")
    for d in (outdir, shard_dir, logdir):
        os.makedirs(d, exist_ok=True)

    stale = [
        f for f in os.listdir(shard_dir) if f.endswith((".parquet", ".db", ".csv"))
    ]
    if stale:
        print(f"\nWarning: {len(stale)} existing shard(s) in {shard_dir}.")
        print("They will be merged with this run's output unless removed:")
        print(f"  rm -f {shard_dir}/*{suffix}")

    manifest = os.path.join(outdir, "census_chunks.json")
    with open(manifest, "w") as f:
        f.write(json.dumps([[r for r, _ in c] for c in chunks], indent=2) + "\n")

    if args.venv:
        env_setup = f'source "{args.venv}/bin/activate"\n'
    elif args.conda_env:
        base = args.conda_base or "$HOME/miniconda3"
        env_setup = (
            f'source "{base}/etc/profile.d/conda.sh"\nconda activate {args.conda_env}\n'
        )
    else:
        env_setup = "# NOTE: no --conda-env/--venv given; the job inherits qsub's environment.\n"

    script = os.path.join(outdir, f"{args.name}_chunk.pbs")
    with open(script, "w") as f:
        f.write(
            PBS_TEMPLATE.format(
                name=args.name,
                account=args.account,
                queue=args.queue,
                select=select,
                place_directive=(f"#PBS -l place={args.place}\n" if args.place else ""),
                rerunnable_directive=f"#PBS -r {args.rerunnable}\n",
                extra_directives="".join(f"#PBS {d}\n" for d in args.pbs),
                walltime=args.walltime,
                filesystems_directive=(
                    f"#PBS -l filesystems={args.filesystems}\n"
                    if args.filesystems
                    else ""
                ),
                logdir=logdir,
                workdir=os.getcwd(),
                env_setup=env_setup,
                manifest=manifest,
                shard_dir=shard_dir,
                suffix=suffix,
                fmt=fmt,
                workers=args.workers,
            )
        )
    os.chmod(script, 0o755)

    last = len(chunks) - 1
    combined = os.path.join(outdir, f"census_combined{suffix}")
    merge_cmd = (
        f"python -m oact_utilities.workflows.census --merge {shard_dir} "
        f"-o {combined} --format {fmt}"
    )

    print(f"\nmanifest : {manifest}")
    print(f"script   : {script}")
    print(f"shards   : {shard_dir}/chunkNN{suffix}")
    print(f"logs     : {logdir}/")
    if args.no_array:
        submit_all = os.path.join(outdir, "submit_all.sh")
        with open(submit_all, "w") as f:
            f.write("#!/usr/bin/env bash\n")
            f.write("# One independent PBS job per chunk (no array job).\n")
            f.write("set -u\n")
            for i in range(len(chunks)):
                f.write(f"qsub -v CENSUS_CHUNK={i} -N {args.name}{i:02d} {script}\n")
        os.chmod(submit_all, 0o755)
        print(f"\nSubmit {len(chunks)} independent jobs:\n  bash {submit_all}")
    else:
        print(f"\nSubmit the array job:\n  qsub -J 0-{last} {script}")
    print(f"\nThen, once every task has finished, merge:\n  {merge_cmd}")
    print(
        "\nThe merge takes seconds and is safe on a login node. Chaining it with\n"
        "  qsub -W depend=afterokarray:<ARRAY_ID> ...\n"
        "also works on PBS Pro, but verify the dependency syntax on your system\n"
        "before relying on it -- this script does not submit the merge for you."
    )

    if args.submit:
        if args.no_array:
            print("\n--submit with --no-array: run the submit_all.sh above instead")
            return 0
        cmd = ["qsub", "-J", f"0-{last}", script]
        print(f"\nSubmitting: {' '.join(cmd)}")
        try:
            out = subprocess.run(cmd, capture_output=True, text=True, check=False)
        except FileNotFoundError:
            print("Error: qsub not found -- run this on a submit host", file=sys.stderr)
            return 1
        sys.stdout.write(out.stdout)
        sys.stderr.write(out.stderr)
        if out.returncode != 0:
            return out.returncode
        print(f"\nWatch with: qstat -t -u $USER\nMerge after: {merge_cmd}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
